---
#-- ./inventory/all.yaml

# ALL HOSTS
# =========
# 
# This file is the main inventory file and is used to define the inventory structure
# for all groups (children). It contains the list of all groups that is used for
# group variables `group_vars`.
#
# Verify the inventory structure with the command `$ ansible-inventory --graph`.
#
# Note: `children` is used to define groups of hosts and `hosts` is used to define 
# individual hosts.

all:
  children:
    debian:
    raspberrypi:
    fedora:
    windows:
    osx: