#-- ./host_vars/firewall.yaml

# FIREWALL HOST VARIABLES
# ====================
#
# Host variables for the firewall host. Variable in this file will supersede variables
# of the same name in group_vars/group and group/vars/all.yaml.
#
# Note: sensitive information should be encrypted with ansible vault

